version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: company_processes
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'

  api:
    build: .
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: rootpass
      DATABASE_NAME: company_processes
    ports:
      - '3000:3000'
    depends_on:
      - db

